Story #13923: Pastis standalone documentation
ProgrammeVitam/vitam-doc pull request #110
Opened 2024-11-22 12:17 UTC by ebernard

Initialisation de la documentation pour Pastis standalone, avec notamment la documentation de l'extension des métadonnées descriptives.

Il reste des informations à ajouter.

2024-11-22 12:27 UTC, GiooDev requested changes

2024-11-22 12:27 UTC, GiooDev commented on source/sections/pastis_standalone.md
> +PASTIS STANDALONE
Titre de niveau 1: `#`

2024-11-22 12:27 UTC, GiooDev commented on source/sections/pastis_standalone.md
> +Résumé
Titre de niveau 2: `##`

2024-11-22 12:27 UTC, GiooDev commented on source/sections/pastis_standalone.md
> +Présentation, installation, et lancement de Pastis Standalone
Titre à retirer ? sinon revoir le niveau des titres suivants et le niveau du titre ici (`###` ?).

2024-11-22 12:27 UTC, GiooDev commented on source/sections/pastis_standalone.md
> +
Saut de ligne en trop.

2024-11-22 12:27 UTC, GiooDev commented on source/sections/pastis_standalone.md
> +
Saut de ligne en trop.

2024-11-22 12:27 UTC, GiooDev commented on source/sections/pastis_standalone.md
> +
Saut de ligne en trop.

2024-11-22 12:27 UTC, GiooDev commented on source/sections/pastis_standalone.md
> +indépendante de la plateforme VITAM.
Saut de ligne inutile.

2024-11-22 12:27 UTC, GiooDev commented on source/sections/pastis_standalone.md
> +Archivistique en ajoutant des champs personnalisés, qui viendront enrichir les informations des unités archivistiques.
Saut de ligne inutile.

2024-11-22 12:27 UTC, GiooDev commented on source/sections/pastis_standalone.md
> +répertoire que le fichier .exe
Saut de ligne inutile.

2024-11-22 12:29 UTC, GiooDev commented
Pour info, j'utilise l'extension `markdownlint` pour vscode afin de vérifier la syntaxe des markdowns :)

2024-11-22 15:27 UTC, ebernard commented on source/sections/pastis_standalone.md
> +Présentation, installation, et lancement de Pastis Standalone
J'ai utilisé la même structure que le doc `resip.md`. Quand il y aura des vrais contenus autre que du blabla ça devrait mieux aller.

2024-11-22 15:27 UTC, ebernard commented
> Pour info, j'utilise l'extension `markdownlint` pour vscode afin de vérifier la syntaxe des markdowns :)

Ok. Moi j'utilise IntelliJ qui me fait la preview en direct et qui ne m'avait pas détecté de problèmes 😀

2024-11-22 15:39 UTC, GiooDev commented
> > Pour info, j'utilise l'extension `markdownlint` pour vscode afin de vérifier la syntaxe des markdowns :)
> 
> Ok. Moi j'utilise IntelliJ qui me fait la preview en direct et qui ne m'avait pas détecté de problèmes 😀

Mon linter doit être plus sensible :p

2024-11-22 15:41 UTC, ebernard commented
> > > Pour info, j'utilise l'extension `markdownlint` pour vscode afin de vérifier la syntaxe des markdowns :)
> > 
> > 
> > Ok. Moi j'utilise IntelliJ qui me fait la preview en direct et qui ne m'avait pas détecté de problèmes 😀
> 
> Mon linter doit être plus sensible :p

Sensible... Ouais on va dire "sensible" 😆

2024-11-22 17:05 UTC, Regzox commented on source/sections/pastis_standalone.md
> +blabla
TODO ?

2024-11-22 17:07 UTC, Regzox commented on source/sections/pastis_standalone.md
> +    "Type": "OBJECT",
On a viré le isObject ?

2024-11-22 17:08 UTC, Regzox approved these changes

2024-11-22 17:11 UTC, ebernard commented on source/sections/pastis_standalone.md
> +blabla
J'ai changé en TODO. Mais il faudra bien mettre du blabla ;-)

2024-11-22 17:13 UTC, ebernard commented on source/sections/pastis_standalone.md
> +    "Type": "OBJECT",
Non, le `isObjet` est bien utilisé dans les schémas, mais il n'est pas nécessaire ici, car on se base sur le type "OBJECT". Voir dans Vitam UI, `src/main/java/fr/gouv/vitamui/pastis/server/service/MetaModelService.java` ligne 123.

2024-11-22 17:17 UTC, GiooDev requested changes

2024-11-22 17:17 UTC, GiooDev commented on source/sections/pastis_standalone.md
> +L'application Pastis Standalone est téléchargeable sur le site internet du programme Vitam à l’adresse suivante : TODO
https://download.programmevitam.fr/pastis-standalone/

2024-11-22 17:36 UTC, GiooDev approved these changes

2024-11-25 17:06 UTC, agrippon approved these changes

2024-11-25 17:07 UTC, merged